export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';

// BDS DISTRICT
export const FETCH_DISTRICT = 'FETCH_DISTRICT';
export const ADD_DISTRICT = 'ADD_DISTRICT';
export const UPDATE_DISTRICT = 'UPDATE_DISTRICT';
export const DELETE_DISTRICT = 'DELETE_DISTRICT';
export const EDIT_DISTRICT = 'EDIT_DISTRICT';


// BDS PROJECT
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';

// BDS NEWS
export const FETCH_NEWS = 'FETCH_NEWS';
export const ADD_NEWS = 'ADD_NEWS';
export const UPDATE_NEWS = 'UPDATE_NEWS';
export const DELETE_NEWS = 'DELETE_NEWS';
export const EDIT_NEWS = 'EDIT_NEWS';

// BDS CONTACT
export const FETCH_CONTACT = 'FETCH_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';

// BDS ABOUT
export const FETCH_ABOUT = 'FETCH_ABOUT';
export const ADD_ABOUT = 'ADD_ABOUT';
export const UPDATE_ABOUT = 'UPDATE_ABOUT';
export const DELETE_ABOUT = 'DELETE_ABOUT';
export const EDIT_ABOUT = 'EDIT_ABOUT';

// BDS USER
export const FETCH_USER = 'FETCH_USER';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';